### ISSUE TITLE
sidebar tabs text never changes

### ISSUE THREAD

**Issue by naumanumer** [naumanumer/easybasic#1]
on saving the document the text of tab is changed but the text of side bar never changes

**Comment by naumanumer** [comment]
fixed and added in next release

**Comment by nmanumr** [comment]
**Project Improvements**
There are following improvements I wanted to make in this project.

* Use [xterm.js](https://xtermjs.org/) from shell instead of implementing our own shell and extend xterm.js for graphics support.
* Use Some Native UI instead of material design. For that, I was writing my own UI components library.
* For full language support I was writing my own monaco-editor extension for BASIC language here was my initial https://github.com/nmanumr/monaco-basic.


I updated the readme and now closing the issue
