### ISSUE TITLE
Difficulty getting started

### ISSUE THREAD

**Issue by joeskeen** [naumanumer/easybasic#1]
Hello @nmanumr, I came across this repository and I'm really interested in the idea of it.  I would like to use this for educational purposes, but I'm having trouble getting it going.  According to the directions in the Readme:

> * Install development node modules with npm install(from project root)
> * Install other mode modules with npm install(Inside app folder)
> * run with npm start

Running `npm install` from project root didn't work, as there is no `package.json` file there, and I couldn't get `npm start` to work anywhere since there is no script named `start` in any `package.json` file.  I did find some `ng serve` scripts in some places, but they didn't work as well, since they weren't in a `package.json` file that referenced the Angular CLI. I did manage to run Electron, but got a window saying that the application didn't load.

I'd be happy to help get this working, but I would appreciate if you could help me understand how to get it running, how things are laid out and the progress on the project.

Thanks!

**Comment by nmanumr** [comment]
try `npm install` in `app` directory.

And these are the script in app directory to run different apps

```
"scripts": {
    "home": "ng serve --port=4200",
    "shell": "ng serve --port=4201",
    "ide": "ng serve --port=4202",
    "electron": "electron ."
  }
```

Run the script for app u wanted to run or run all these in different terminals. Actually, this documentation was written for its previous version that can be found in branch `release-4.0`. You can also check that out

I wanted to continue this project but because of lack of time but I am not able to do so. If u are interested in this u can even seek my help.
